language: python
dist: trusty
python:
  - "3.6"

before_install:
  - sudo apt-get install software-properties-common wget
  - sudo add-apt-repository universe
  - wget http://apt-stable.ntop.org/18.04/all/apt-ntop-stable.deb
  - sudo apt install ./apt-ntop-stable.deb
  - rm apt-ntop-stable.deb
  - sudo apt-get update
  - sudo apt-get install -y build-essential mongodb pfring lsb-release libnuma-dev
  - pip install cython
  - pip install -r requirements.txt


install:
  - python setup.py install

script:
  - python -c "print(\"Hello Travis\")"
